using System.Text.Json;
using System.Text.Json.Serialization;

namespace Festival.Core.Domain;

#region Manifest
/// <summary>One acknowledged package in <c>Assets/licenses.json</c> (generated by <c>tools/windows/licenses.py</c>).</summary>
public sealed record LicensePackage
{
    /// <summary>NuGet ID or asset ID.</summary>
    [JsonPropertyName("id")] public string Id { get; init; } = "";
    /// <summary>Display name.</summary>
    [JsonPropertyName("name")] public string Name { get; init; } = "";
    /// <summary>Version or role.</summary>
    [JsonPropertyName("version")] public string Version { get; init; } = "";
    /// <summary>Ecosystem (NuGet, Bundled asset).</summary>
    [JsonPropertyName("ecosystem")] public string Ecosystem { get; init; } = "";
    /// <summary>License label.</summary>
    [JsonPropertyName("license")] public string License { get; init; } = "";
    /// <summary>Project URL, if known.</summary>
    [JsonPropertyName("url")] public string? Url { get; init; }
    /// <summary>Key into <see cref="LicenseManifest.Texts"/>.</summary>
    [JsonPropertyName("textId")] public string TextId { get; init; } = "";
}

/// <summary>The generated manifest: packages plus de-duplicated license bodies.</summary>
public sealed record LicenseManifest
{
    /// <summary>Schema version.</summary>
    [JsonPropertyName("schemaVersion")] public int SchemaVersion { get; init; }
    /// <summary>Packages.</summary>
    [JsonPropertyName("packages")] public List<LicensePackage> Packages { get; init; } = [];
    /// <summary>License bodies by ID.</summary>
    [JsonPropertyName("texts")] public Dictionary<string, string> Texts { get; init; } = [];

    /// <summary>First-party bundled assets listed for transparency (they carry no third-party license).</summary>
    public static IReadOnlyList<(LicensePackage Package, string Text)> BundledAssets { get; } =
    [
        (new LicensePackage
        {
            Id = "instrument-iconography", Name = "Instrument Iconography", Version = "Assets/Instruments",
            Ecosystem = "Bundled asset", License = "First-party", TextId = "first-party",
        },
        "These instrument icons are the operator's own artwork, copied from the companion website's public/instruments/ " +
        "directory (the same origin as this app's service). They are not third-party assets, are not licensed from another " +
        "rights holder, and this app does not bundle any third-party album art or trademarked imagery."),
    ];

    /// <summary>Parses and validates manifest bytes; anything malformed yields an empty manifest.</summary>
    /// <param name="bytes">File bytes, or <see langword="null"/> when missing.</param>
    /// <returns>Manifest whose packages all reference a known text.</returns>
    public static LicenseManifest Parse(byte[]? bytes)
    {
        if (bytes is not { Length: > 0 and <= 2_000_000 }) return new LicenseManifest();
        try
        {
            var manifest = JsonSerializer.Deserialize(bytes, LicensesJsonContext.Default.LicenseManifest) ?? new LicenseManifest();
            var texts = manifest.Texts ?? [];
            return manifest with
            {
                Texts = texts,
                Packages = (manifest.Packages ?? []).Where(p => p is { Name.Length: > 0 } && texts.ContainsKey(p.TextId ?? "")).ToList(),
            };
        }
        catch (JsonException)
        {
            return new LicenseManifest();
        }
    }
}
#endregion
