// Generated by tools/generate_tokens.py from contracts/fluent-tokens.json.
import SwiftUI

/// Brand content colors; system chrome and accessibility overrides remain native.
public enum BrandTokens {
    public static let accentBlue = Color(.sRGB, red: 45.0 / 255, green: 130.0 / 255, blue: 230.0 / 255, opacity: 255.0 / 255)
    public static let accentPurple = Color(.sRGB, red: 124.0 / 255, green: 58.0 / 255, blue: 237.0 / 255, opacity: 255.0 / 255)
    public static let appBackground = Color(.sRGB, red: 26.0 / 255, green: 8.0 / 255, blue: 48.0 / 255, opacity: 255.0 / 255)
    public static let cardBackground = Color(.sRGB, red: 11.0 / 255, green: 18.0 / 255, blue: 32.0 / 255, opacity: 255.0 / 255)
    public static let glassBorder = Color(.sRGB, red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, opacity: 20.0 / 255)
    public static let gold = Color(.sRGB, red: 255.0 / 255, green: 215.0 / 255, blue: 0.0 / 255, opacity: 255.0 / 255)
    public static let statusGreen = Color(.sRGB, red: 46.0 / 255, green: 204.0 / 255, blue: 113.0 / 255, opacity: 255.0 / 255)
    public static let statusRed = Color(.sRGB, red: 198.0 / 255, green: 40.0 / 255, blue: 40.0 / 255, opacity: 255.0 / 255)
    public static let surfaceFrosted = Color(.sRGB, red: 18.0 / 255, green: 24.0 / 255, blue: 38.0 / 255, opacity: 199.0 / 255)
    public static let textMuted = Color(.sRGB, red: 136.0 / 255, green: 153.0 / 255, blue: 170.0 / 255, opacity: 255.0 / 255)
    public static let textPrimary = Color(.sRGB, red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, opacity: 255.0 / 255)
    public static let textSecondary = Color(.sRGB, red: 215.0 / 255, green: 222.0 / 255, blue: 232.0 / 255, opacity: 255.0 / 255)
}
