#!/usr/bin/env python3
"""Generate native Swift, Compose and WinUI color resources from one contract."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "contracts/fluent-tokens.json"
OUTPUTS = {
    "swift": ROOT / "apple/Sources/FestivalDesign/BrandTokens.swift",
    "kotlin": ROOT / "contracts/generated/android/BrandTokens.kt",
    "xaml": ROOT / "contracts/generated/windows/BrandTokens.xaml",
}
HEX = re.compile(r"^#([0-9A-Fa-f]{6})$")
RGBA = re.compile(r"^rgba\((\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3}),\s*(0(?:\.\d+)?|1(?:\.0+)?)\)$")


def parse_color(value: str) -> tuple[int, int, int, int]:
    """Parse a source CSS color into unambiguous eight-bit ARGB components.

    Args:
        value: `#RRGGBB` or `rgba(r,g,b,a)` source token.

    Returns:
        Alpha, red, green and blue bytes in that order.

    Raises:
        ValueError: For unsupported, out-of-range or ambiguous colors.
    """
    hex_match = HEX.fullmatch(value)
    if hex_match:
        rgb = hex_match.group(1)
        return (255, *(int(rgb[index:index + 2], 16) for index in (0, 2, 4)))
    rgba_match = RGBA.fullmatch(value)
    if rgba_match:
        red, green, blue = (int(rgba_match[index]) for index in (1, 2, 3))
        alpha = float(rgba_match[4])
        if any(channel > 255 for channel in (red, green, blue)):
            raise ValueError(f"out-of-range channel in {value}")
        return (round(alpha * 255), red, green, blue)
    raise ValueError(f"unsupported color {value!r}")


def render_swift(colors: dict[str, tuple[int, int, int, int]]) -> str:
    """Produce semantic Apple Color constants without duplicating token values.

    Args:
        colors: Parsed color components by semantic name.

    Returns:
        Compilable SwiftUI source.
    """
    lines = [
        "// Generated by tools/generate_tokens.py from contracts/fluent-tokens.json.",
        "import SwiftUI",
        "",
        "/// Brand content colors; system chrome and accessibility overrides remain native.",
        "public enum BrandTokens {",
    ]
    for name, (alpha, red, green, blue) in sorted(colors.items()):
        lines.append(
            f"    public static let {name} = Color(.sRGB, red: {red}.0 / 255, "
            f"green: {green}.0 / 255, blue: {blue}.0 / 255, "
            f"opacity: {alpha}.0 / 255)"
        )
    return "\n".join(lines + ["}", ""])


def render_kotlin(colors: dict[str, tuple[int, int, int, int]]) -> str:
    """Produce Compose Color values in the shared Android design namespace.

    Args:
        colors: Parsed color components by semantic name.

    Returns:
        Compilable Kotlin source.
    """
    lines = [
        "// Generated by tools/generate_tokens.py from contracts/fluent-tokens.json.",
        "package com.sfenton.festival.design",
        "",
        "import androidx.compose.ui.graphics.Color",
        "",
        "/** Semantic Festival content colors; keep system surfaces adaptive. */",
        "object BrandTokens {",
    ]
    for name, (alpha, red, green, blue) in sorted(colors.items()):
        lines.append(f"    val {name} = Color(0x{alpha:02X}{red:02X}{green:02X}{blue:02X})")
    return "\n".join(lines + ["}", ""])


def render_xaml(colors: dict[str, tuple[int, int, int, int]]) -> str:
    """Produce WinUI colors and brushes for Fluent semantic resources.

    Args:
        colors: Parsed color components by semantic name.

    Returns:
        A WinUI 3 ResourceDictionary with Color and SolidColorBrush keys.
    """
    lines = [
        "<!-- Generated by tools/generate_tokens.py from contracts/fluent-tokens.json. -->",
        '<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
        '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
    ]
    for name, (alpha, red, green, blue) in sorted(colors.items()):
        key = name[0].upper() + name[1:]
        lines.append(
            f'    <Color x:Key="FST{key}Color">#{alpha:02X}{red:02X}{green:02X}{blue:02X}</Color>'
        )
        lines.append(
            f'    <SolidColorBrush x:Key="FST{key}Brush" Color="{{StaticResource FST{key}Color}}" />'
        )
    return "\n".join(lines + ["</ResourceDictionary>", ""])


def main(argv: list[str] | None = None) -> int:
    """Write generated resources or fail if checked-in copies drift.

    Args:
        argv: Optional command-line arguments; None uses the process arguments.

    Returns:
        Zero if every generated file matches the token contract.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Do not write; detect drift")
    args = parser.parse_args(argv)
    try:
        data = json.loads(CONTRACT.read_text(encoding="utf-8"))
        if data.get("schemaVersion") != 1 or not isinstance(data.get("colors"), dict):
            raise ValueError("invalid token contract")
        if not data["colors"] or not all(
            isinstance(name, str) and name.isidentifier() and isinstance(color, str)
            for name, color in data["colors"].items()
        ):
            raise ValueError("invalid semantic color tokens")
        colors = {name: parse_color(value) for name, value in data["colors"].items()}
        rendered = {
            "swift": render_swift(colors),
            "kotlin": render_kotlin(colors),
            "xaml": render_xaml(colors),
        }
        for kind, path in OUTPUTS.items():
            if args.check:
                if not path.is_file() or path.read_text(encoding="utf-8") != rendered[kind]:
                    raise ValueError(f"{path.relative_to(ROOT)} differs from token contract")
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(rendered[kind], encoding="utf-8")
    except (OSError, json.JSONDecodeError, ValueError) as error:
        print(f"Token generation failed: {error}", file=sys.stderr)
        return 1
    print("Native design tokens match the versioned contract.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
